/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pager.duty.core;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PagerDutyCoreAppTest {
    @Test void appHasAGreeting() {
        PagerDutyCoreApp classUnderTest = new PagerDutyCoreApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
