/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pager.duty.core;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class PagerDutyCoreApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SpringApplication.run(PagerDutyCoreApp.class, args);
    }
}
